### ISSUE TITLE
LoginManager must use interface AccessTokenStorage and not class AccessTokenManager

### ISSUE THREAD

**Issue by VMitin** [uber/rides-android-sdk#101]
Hi there! 

I want to implement AccessTokenStorage for saving token details myself, but I can't! 
LoginManager uses class AccessTokenManager but must use the interface. Please, fix it. Thanks

**Comment by tyvsmith** [comment]
Thanks @VMitin, we're just now picking this project up after being under-resourced for a while. I'll be making some headway on the reported issues after a bit more fundamental changes are completed. Should be next week or the following.
