### ISSUE TITLE
Uber SDK Android Sign in

### ISSUE THREAD

**Issue by imprashanthguru** [uber/rides-android-sdk#103]
How do I sign in to to the app? I've been trying to integrate Uber SDK with android.  
What goes inside the login listeners? I've used SessionManagement, AccessTokenStorage. I've already generated rhe SHA1 Key and got the redirect URI, other values. Should I send the .APK Key to Uber?

**Comment by tyvsmith** [comment]
Hey @imprashanthguru, Github is only for bug reports. Please use Stackoverflow with the uber-api tag for product help.
