### ISSUE TITLE
Login Button does not change to Sign Out after user gets logged in

### ISSUE THREAD

**Issue by RahulSakaria** [uber/rides-android-sdk#104]
The login button in the SDK doesn't change to Sign Out when the onLoginSuccess is perfectly working.
How to solve this. Please help me `fix` this issue ASAP.

`LoginButton loginButton = findViewById(R.id.login_button);
        loginButton.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View view) {
            LoginCallback loginCallback = new LoginCallback() {
                @Override
                public void onLoginCancel() {

                }

                @Override
                public void onLoginError(@NonNull AuthenticationError error) {

                }

                @Override
                public void onLoginSuccess(@NonNull AccessToken accessToken) {
                    Toast.makeText(MainActivity.this,"Success",Toast.LENGTH_SHORT).show();  
                }

                @Override
                public void onAuthorizationCodeReceived(@NonNull String authorizationCode) {

                }
            };
                AccessTokenManager accessTokenManager = new AccessTokenManager(getApplicationContext());
                loginManager = new LoginManager(accessTokenManager, loginCallback);
                loginManager.login(MainActivity.this);
            }

        });

    }
    @Override
    protected void onActivityResult(int requestCode, int resultCode, Intent data){
        super.onActivityResult(requestCode, resultCode, data);
        loginManager.onActivityResult(MainActivity.this, requestCode, resultCode, data);
    }
}``

**Comment by tyvsmith** [comment]
The Login button does not have the feature to change to Logout. That would need to be a custom implementation. 

If you would like to contribute this feature, please start a thread with a design proposal and we'd be happy to chat about taking a PR.
