### ISSUE TITLE
Uber RideRequestButton does not show the time and fare estimate for other cities. It shows for California but not for Cincinati and major of the other cities. Is all the cities included in the UBER SDK ?

### ISSUE THREAD

**Issue by RahulSakaria** [uber/rides-android-sdk#114]
``   SessionConfiguration config = new SessionConfiguration.Builder()
                // mandatory
                .setClientId("<MyCLientID>")
                // required for enhanced button features
                .setServerToken("<MyServerToken>")
                // required for implicit grant authentication
                //.setRedirectUri("<REDIRECT_URI>")
                // required scope for Ride Request Widget features
                .setScopes(Arrays.asList(Scope.RIDE_WIDGETS))
                // optional: set sandbox as operating environment
                .setEnvironment(SessionConfiguration.Environment.PRODUCTION)
                .build();

        UberSdk.initialize(config);
        RideRequestButton requestButton = findViewById(R.id.uber_button_plan_a_trip);

        RideParameters rideParams = new RideParameters.Builder()
                // Optional product_id from /v1/products endpoint (e.g. UberX). If not provided, most cost-efficient product will be used
                .setProductId("a1111c8c-c720-46c3-8534-2fcdd730040d")
                // Required for price estimates; lat (Double), lng (Double), nickname (String), formatted address (String) of dropoff location
                .setDropoffLocation(
                        destinationLat, destinationLon, "", "")
                // Required for pickup estimates; lat (Double), lng (Double), nickname (String), formatted address (String) of pickup location
                .setPickupLocation(sourceLat, sourceLon, "", "")
                .build();
// set parameters for the RideRequestButton instance
        requestButton.setRideParameters(rideParams);
        ServerTokenSession session = new ServerTokenSession(config);
        requestButton.setSession(session);
        requestButton.loadRideInformation();

**Comment by tyvsmith** [comment]
For help, please post on [stackoverflow with the uber-api tag](https://stackoverflow.com/questions/tagged/uber-api).

First glance though, is that you're using a product ID that's not available in those markets. You'll want to query what product ids are available in the current market before specifying them in the param builder.
