### ISSUE TITLE
sdk 0.9.1 redirect url's registration issue

### ISSUE THREAD

**Issue by luckcoolla** [uber/rides-android-sdk#119]
Hello,
I'm updating working project's Uber sdk integration, the auth part.
In our project we are using only web-view(or chrometab) method - LoginManager#loginForAuthorizationCode(Activity) method.

I've tried to follow your steps https://github.com/uber/rides-android-sdk#authentication-migration-and-setup-version-08-and-above 
But there is an issue - I cann't register  URI (with the format "applicationId.uberauth")on the  developer dashboard - it marks this attempt as failed: 
"At least one redirect URI is required if any default ride scopes are provided. In addition each redirect URI must be a valid URI and the HTTP scheme is only allowed for localhost or 127.0.0.1."

Library version: 0.9.1

Repro steps, stacktrace, screenshots:
Follow these steps: https://github.com/uber/rides-android-sdk#authentication-migration-and-setup-version-08-and-above
Expected Behavior: I should be able to reproduce pointed steps

**Comment by tyvsmith** [comment]
A valid Redirect URI would be "com.example.uberauth://redirect". Please register that. It looks like the readme needs to be fixed.

**Comment by luckcoolla** [comment]
@tyvsmith perfect, thank you
