### ISSUE TITLE
The uri generated by the class RequestDeeplink is encoded

### ISSUE THREAD

**Issue by panleicim** [uber/rides-android-sdk#12]
Hello, 

I've tried to use ReuqestDeeplink class of the SDK to launch Uber application with parameters, but i found that the generated uri is **encoded**.

For example:
uber:?action=setPickup&client_id=OuIucGjvQ8F6rfluPyopzdazZihlaGdT&pickup%5Blatitude%5D=48.80373&pickup%5Blongitude%5D=2.2957778&dropoff%5Blatitude%5D=48.86018&dropoff%5Blongitude%5D=2.350931&dropoff%5Bformatted_address%5D=Place%20Georges%20POMPIDOU%20%2075004%20PARIS%2004&user-agent=rides-deeplink-v0.2.0

Well, the correct uri should be like :
uber://?client_id=YOUR_CLIENT_ID&action=setPickup&pickup[latitude]=37.775818&pickup[longitude]=-122.418028&pickup[nickname]=UberHQ&pickup[formatted_address]=1455%20Market%20St%2C%20San%20Francisco%2C%20CA%2094103&dropoff[latitude]=37.802374&dropoff[longitude]=-122.405818&dropoff[nickname]=Coit%20Tower&dropoff[formatted_address]=1%20Telegraph%20Hill%20Blvd%2C%20San%20Francisco%2C%20CA%2094133&product_id=a1111c8c-c720-46c3-8534-2fcdd730040d

**Comment by tyvsmith** [comment]
Thanks for reporting @panleicim, we will investigate and respond soon.

**Comment by tyvsmith** [comment]
Hi @panleicim. What version of Android are you testing this on and what version of the Uber App do you have installed? I'm trying to repro this and the expectation is that Android URI is stored encoded.

**Comment by tyvsmith** [comment]
Closing this without more repro data.
