### ISSUE TITLE
Documentation Error in section Adding Parameters

### ISSUE THREAD

**Issue by hanuor** [uber/rides-android-sdk#14]
Kindly take a look at this LOC and try to change it at the earliest ...
In Adding Parameters
RequestButton requestButton = RequestButton(context);

change it to - 
RequestButton requestButton =  new RequestButton(context);
Hope this gets corrected ASAP.

**Comment by itstexter** [comment]
Thanks for catching this, we renamed the buttons and fixed this part of the README in release [v0.3.0](https://github.com/uber/rides-android-sdk/releases/tag/v0.3.0)
