### ISSUE TITLE
NullPointerException when login via SSO without setting product flow priority

### ISSUE THREAD

**Issue by AlexBonel** [uber/rides-android-sdk#153]
Library version: **0.10.0**

Repro steps, stacktrace, screenshots: 

1. Assign any application's certificate footprint in uber developer's settings to enable SSO.
2. Integrate the sdk in your project
3. call `LoginManager.login()`

Expected Behavior: launching of Uber app with login activity

Real result: NPE crash

```
java.lang.NullPointerException: collection == null
        at java.util.ArrayList.<init>(ArrayList.java:94)
        at com.uber.sdk.android.core.auth.LoginManager.login(LoginManager.java:180)
```

The cause is the default value of `productFlowPriority` collection which is `null` and therefore while constructing `ArrayList` it crashes the app.

I would like to know if it's ok to pass to `setProductFlowPriority()` `Collections.emptyList()` to bypass the crash ?

**Comment by thepoofy** [comment]
Yes, passing `Collections.emptyList()` should be fine.  This will default you to using only the Uber app.
