### ISSUE TITLE
On login - INVALID_SCOPE

### ISSUE THREAD

**Issue by OleksandrGrument** [uber/rides-android-sdk#173]
Hello i'm trying to implement uber login according to samples and i'm getting every time error INVALID_SCOPE. What does this error mean ? How to prevent it ?

I'm getting invalid scope in
 public void onLoginError(@NonNull AuthenticationError error)

here is the code I use 

`   SessionConfiguration configuration = new SessionConfiguration.Builder()
                .setClientId(getString(R.string.uber_key))
                .setRedirectUri("com.myapp.nyapplication.uberauth://redirect")
                .setScopes(Arrays.asList(Scope.PROFILE, Scope.RIDE_WIDGETS))
                .build();

        AccessTokenManager accessTokenStorage = new AccessTokenManager(this);

        uberLoginManager = new com.uber.sdk.android.core.auth.LoginManager(accessTokenStorage, new UberCallBack(),
                configuration, 1113);

        uberLoginManager.login(this);`
Library version:
0.10.1
Repro steps, stacktrace, screenshots:
[https://imgur.com/a/xUrk4lK](url)
Expected Behavior:
Get access token on success

**Comment by OleksandrGrument** [comment]
Forked the sample login project and put there client id and redirect uri and have the same INVALID_SCOPE on the 3 different types of buttons. It seems like a bug in uber app or in sdk.

**Comment by tiper** [comment]
Hi @OleksandrGrument You probably need to contact Uber Business Development to have access to scopes

**Comment by tipa** [comment]
How to contact Uber Business Development @tiper? I haven't found any links / emails / forms...

**Comment by rachittiwari8562** [comment]
@OleksandrGrument were you able to contact "Uber Business Development" ?
