### ISSUE TITLE
Unable to signup in widget

### ISSUE THREAD

**Issue by arnedevries** [uber/rides-android-sdk#18]
Hi,

We are currently implementing Uber integration using the Android widget in our app, and we noticed it's not possible to signup from inside the widget. After filling out the signup form, the Create Account button remains greyed out. We suspect this is caused by the fact that the selected country code for the mobile number isn't actually set to the drop down field.

![screenshot_2016-05-11-12-26-05](https://cloud.githubusercontent.com/assets/233939/15178128/24f106c0-1774-11e6-9c24-7205ad0c3fd1.png)

Reproduced on a Nexus 4 and an LG G5, in both our own app and in the sample app, both sandbox enabled and disabled. Please let me know if you need any more information.

Arne

**Comment by arogal** [comment]
Thanks Arne. I've confirmed this as well and we are working on a fix.

**Comment by arogal** [comment]
This is now fixed in 0.3.2. Thanks.
