### ISSUE TITLE
**REQUEST FOR DEVELOPMENT OF PLUGIN FOR FLUTTER PLATFORM**

### ISSUE THREAD

**Issue by Manishmg3994** [uber/rides-android-sdk#189]
**REQUEST FOR DEVELOPMENT OF PLUGIN FOR FLUTTER PLATFORM**
DEAR DEVELOPERS , I WISH YOU ARE ADOPTING A NEW WAY TO MAKE YOUR BUSINESS SUCCEED  BUT  I FOUND A PROBLEM  WHICH CAN BE STATED As I WAS UNABLE TO FIND THE INTEGRATION FOR FLUTTER APP ONLY API INTEGRATION IS available BUT AS technologies GROWS THERE SHOULD BE SOME SIMPLIFICATION FOR CODES,SO I WISH YOU CAN MAKE A PLUGIN FOR ALL THE UBER PRODUCTS LIKE RIDE ,EATS FOR FLUTTER (pub.dev)

**Comment by nareshg01** [comment]
Urgent

Hi Team,

I am creating a flutter mobile app,  now I want to implement uber in my app(android and IOS), Is there any help document for this, I am using flutter's latest version 3

**Comment by Manishmg3994** [comment]
@nareshg01 I think Uber stopped those services for some security reasons , Now we can't implement those cab booking services in our Apps
