### ISSUE TITLE
How to get all products at given geo location

### ISSUE THREAD

**Issue by chandrayya** [uber/rides-android-sdk#20]
1. How I can iterate all available products at given geo location using this sdk?Import all module in android studio. Is there any addition dependency do I need to add?
2. Also getting 'Auth error INVALID_APP_SINGNATURE' in request ride example. How to resolve this?

**Comment by itstexter** [comment]
Hey @chandrayya 

To iterate over products for a given geo location, you can create a `Call` object from your `RidesService` with `Call<ProductsResponse> call = ridesService.getProducts(lat, long)`.  You can either enqueue or execute your call, and with the response get the list of products, for example, `call.execute().body().getProducts()`.  You can read more about how to work with the `RidesService` and it's various endpoints at the [Uber Java SDK](https://github.com/uber/rides-java-sdk).

It seems like you haven't registered your application's signature on the [developer dashboard](https://developer.uber.com/dashboard) yet.  From the README:

To use Single Sign On you must register a hash of your application's signing certificate in the Application Signature section of the [developer dashboard] (https://developer.uber.com/dashboard).

To get the hash of your signing certificate, run this command with the alias of your key and path to your keystore:

```sh
keytool -exportcert -alias <your_key_alias> -keystore <your_keystore_path> | openssl sha1 -binary | openssl base64
```
