### ISSUE TITLE
Add additional error logging when invalid app signature is returned.

### ISSUE THREAD

**Issue by tyvsmith** [uber/rides-android-sdk#23]
To facilitate better developer onboarding, we need better logging around app signature and updating it on the developer dashboard.

**Comment by itstexter** [comment]
Fixed in [v0.5.1](https://github.com/uber/rides-android-sdk/releases/tag/v0.5.1)

**Comment by khuranakaran** [comment]
I'm getting INVALID_APP_SIGNATURE, my app is in building phase. In some devices it works fine but in some it doesn't. Is there anything that can be done without facing this trouble again ?

**Comment by jaggi772** [comment]
Using v0.5.3 but again "Invalid App Signature" error if uber app is present in device otherwise not getting such error if i  remove app from device. Not able to find reason. I have also added App signatures for debug and release in Uber developer console.

**Comment by Technamental** [comment]
I have the same error as jaggi772. I have all of my keys/certs in Uber Dev site, they are valid for another 20 years+, but getting the Uber API error INVALID_APP_SIGNATURE
