### ISSUE TITLE
The ride request is always processing

### ISSUE THREAD

**Issue by linzhe0501** [uber/rides-android-sdk#29]
Polling the Uber API to get the current status every 4 seconds,I always get the response : 
`{
     “status":"processing",
     "product_id":"...",
     "request_id":"...",
     "driver":null,
     "eta":null,
     "location":null,
     "vehicle":null,
     "surge_multiplier":1.0,
     "shared":false}`
The status is always processing. I failed to solve it . Can you help me ?

**Comment by itstexter** [comment]
I think you might be running the service in a sandbox environment.  When this is the case, you have to manually make changes to your ride's status via `RidesService#updateSandboxRide` method, as detailed in the [Rides Java SDK's README](https://github.com/uber/rides-java-sdk/blob/master/README.md) as well as the [developer documentation](https://developer.uber.com/docs/rides/sandbox).

For example, you can try updating your sandbox ride with

`SandboxRideRequestParameters rideParameters = new SandboxRideRequestParameters.Builder().setStatus(“accepted”).build();
Response<Void> response = service.updateSandboxRide(rideId, rideParameters).execute();`

Please let me know if you're still having any issues!  If you don't want to run in the sandbox, set the environment to `PRODUCTION` in your `SessionConfiguration`

**Comment by linzhe0501** [comment]
Thank you for you help.I have solved it.
