### ISSUE TITLE
Plugin with id 'cobertura' not found while adding sdk as module

### ISSUE THREAD

**Issue by bhuvi1991** [uber/rides-android-sdk#32]
I am getting error 

> Error:(5, 0) Plugin with id 'cobertura' not found

 if i add the sdk as module in project rather than dependency because i want to update design of Ride Request Button.How can i resolve this and is there any  way to update text Colour of Ride Request Button if i add sdk directly as gradle dependency rather than module?

**Comment by tyvsmith** [comment]
The cobertura plugin is provided as a buildscript dependency in the [root build.gradle](https://github.com/uber/rides-android-sdk/blob/master/build.gradle) file for all subprojects. If you are pulling out use the submodule directly, you must meet the expected dependencies.
