### ISSUE TITLE
Login redirection problem

### ISSUE THREAD

**Issue by sebztas** [uber/rides-android-sdk#36]
I've encountered an issue with authentication flow.
1. Uber app is installed on the device
2. Start SSO flow from third party app with REQUEST scope and redirection URL in Uber dashboard "http://localhost"
3. User app show login and registration possibilities
4. User tap on login button
5. And login through G+ account
6. User is redirect to home screen of Uber app

* After G+ login user should be redirected to scope confirmation view then to third party app but this is not happening.

**Comment by tyvsmith** [comment]
Thanks for reporting, we will investigate this. To help expedite, does this happen with other sign in flows, or just G+? Secondly, does this happen on the most recent version of the Uber app from the Play store? 

Thanks!

**Comment by sebztas** [comment]
I didn't check it with another flows because i don't have another account to test currently. 
I test it with uber app downloaded 2-3 days ago, is it the most recent one?
* I forgot to mention previously that if above issue occurs then every call of LoginManager.login(..) directs to the Uber App home screen, without scopes confirmation screen. If we want to leave Uber App after click on system back button, onLoginCancelled is called. 

Hope it helps!

**Comment by tyvsmith** [comment]
This is on the roadmap and will be addressed in a future app release.

**Comment by sebztas** [comment]
When the new app will be released, with that fix?

**Comment by itstexter** [comment]
I did some more investigating on this and it is definitely an issue that needs to be fixed in a future app release, unfortunately we don't know the timeline for when this will get in. I will ping this thread when it gets released. Sorry I can't be more concise!

**Comment by sebztas** [comment]
Ok, I will be patiently waiting for the info :)
