### ISSUE TITLE
Unable to download sdk in gradle 

### ISSUE THREAD

**Issue by shahjahank08** [uber/rides-android-sdk#37]
Hi 

i am getting below error while sync Gradle build 

Could not find core-android.jar (com.uber.sdk:core-android:0.5.2).
  Searched in the following locations:
      https://jcenter.bintray.com/com/uber/sdk/core-android/0.5.2/core-android-0.5.2.jar

**Comment by tyvsmith** [comment]
The Uber SDKs are hosted in Maven Central, not JCenter. Please be sure to include mavenCentral() in your dependencies block. 

http://search.maven.org/#artifactdetails%7Ccom.uber.sdk%7Ccore-android%7C0.5.2%7Caar
