### ISSUE TITLE
Ride Requests for ionic cordova framework

### ISSUE THREAD

**Issue by nadeemkhan** [uber/rides-android-sdk#39]
Is it possible to integrate  Ride Requests - API into ionic framework if yes then how can we get started?

**Comment by arogal** [comment]
Hi Nadeem,

**Comment by arogal** [comment]
Hey Nadeem,

We'll research and get back to you on if it's compatible.

**Comment by nadeemkhan** [comment]
Thanks Adam :)

**Comment by tyvsmith** [comment]
Hey @nadeemkhan. We don't have short term plans to add first party support for Cordova or other cross compiling frameworks, however most web based cross compiling frameworks have a plugin system to allow for native interactions. [This section](http://cordova.apache.org/docs/en/3.6.0/guide/hybrid/plugins/index.html#Plugin%20Development%20Guide) from their docs looks like what you might be interested in.
