### ISSUE TITLE
onclick listener of RequestButton?

### ISSUE THREAD

**Issue by mopa11** [uber/rides-android-sdk#4]
I have implemented Request Button but i want click listener to perform other task related to my app.

**Comment by mnemonicflow** [comment]
@mopa11 See pull request #5

**Comment by itstexter** [comment]
We need to plan on how we want to handle external provided onclicks on top of the provided functionality still. Pull req #5 ended up diverging a bit away from that still, so for now will be looking at the roadmap for that and pinging the thread when a change comes out
