### ISSUE TITLE
Ride Request Widget Issue

### ISSUE THREAD

**Issue by lawloretienne** [uber/rides-android-sdk#46]
So a dialog keeps showing that says `The Ride Request Widget encountered a problem`.  It has two buttons `CANCEL` and `TRY AGAIN`.  My pick up location is in Los Angeles and the drop off location is in Las Vegas.  What is causing this dialog to show?  I am able to view the Request Widget if both my pick up and drop off location are in Los Angeles.

**Comment by itstexter** [comment]
I believe trips over 100 miles aren't allowed through the Ride Request Widget. It is supposed to show an error within the widget (something like "pickup and dropoff can't be over 100 miles, please change your dropoff") but it seems like there is a bug with how the mobile app is notified about this problem from the Ride Request Widget so the whole widget errors out.

I'll look into fixing this, thanks for letting us know!

**Comment by lawloretienne** [comment]
Thanks for letting me know.  Yes an error message like that would be a much better user experience.

**Comment by itstexter** [comment]
Fixed in [v0.5.3](https://github.com/uber/rides-android-sdk/releases/tag/v0.5.3)

**Comment by Vinod-patil570** [comment]
Hi , Can anyone help me out ??

My issue is , when i click "Get a ride button " Widget is not working in my Android app its displaying "Unable to connect , which has "okay" button when clicked other popup comes up which says "There was a problem authenticating you . But deep linking with ride params is working fine .

Thanks .
