### ISSUE TITLE
Sign Up issue on ride request widget

### ISSUE THREAD

**Issue by Vipulmittal102** [uber/rides-android-sdk#52]
While signing up for Uber in widget with cash payment, it is not verifying phone number.
Please check. Widget version is "com.uber.sdk:rides-android:0.3.2"

**Comment by agraebe** [comment]
@Vipulmittal102 Could you please provide more details along with code snippets and the steps you're making. We would like to reproduce this error but we lack details. Thanks!

**Comment by Vipulmittal102** [comment]
Hi,

PFA image showing when this issue arises.
![screenshot_20160916-153042](https://cloud.githubusercontent.com/assets/18523507/18583328/98068fa0-7c27-11e6-90bc-18b4a85eac98.png)

Just calling login widget when user is not logged in:

 mLoginManager = new LoginManager(mAccessTokenManager);
        List<Scope> scopes = new ArrayList<Scope>();
        scopes.add(Scope.RIDE_WIDGETS);
        scopes.add(Scope.PROFILE);
        mLoginManager.loginWithScopes(this, scopes);

**Comment by Vipulmittal102** [comment]
Any update here???

**Comment by alecmgo** [comment]
Sorry for the delay. Can you also provide the error message that you're receiving?

**Comment by tyvsmith** [comment]
@Vipulmittal102 While one of our backend teams is investigating the reported issue, I noticed you're using version com.uber.sdk:rides-android:0.3.2 of the SDK. Please update to the most current.

**Comment by itstexter** [comment]
Hey @Vipulmittal102 we're having trouble reproducing this on our end, can you clarify the exact steps to get this to happen? It sounds like you try to open the ride request widget without Uber installed and click sign up on the login screen, can you clarify what you do after that?

**Comment by Vipulmittal102** [comment]
Hey Alex,

Yes I used it without uber app installed. So, won't verification would work
without this?

When I signed up, it asked me to enter verification code sent through sms,
but code didn't come.

Thanks

**Comment by itstexter** [comment]
So sorry for the delay on this, when you say when you signed up, how exactly did you get to the sign up page?

I'm having trouble getting to a sign up page where I can choose cash.

**Comment by tyvsmith** [comment]
Hi @Vipulmittal102, did you try this with an updated version of the SDK. In my recollection, the version you mentioned didn't have Javascript enabled on the webview, which could cause this issue. Please try with 0.5.3 or greater

Thanks!
