### ISSUE TITLE
SSO won't work after reinstall Uber app 

### ISSUE THREAD

**Issue by jaredzhang** [uber/rides-android-sdk#53]
Phone Model: Nexus 5
Steps to replicate:
1 Uninstall and reinstall uber app
2 Try SSO from third party app

```
SsoDeeplink ssoDeeplink = new SsoDeeplink.Builder(activity)
                .clientId(sessionConfiguration.getClientId())
                .region(sessionConfiguration.getEndpointRegion())
                .scopes(sessionConfiguration.getScopes())
                .customScopes(sessionConfiguration.getCustomScopes())
                .activityRequestCode(requestCode)
                .build();
        if (ssoDeeplink.isSupported()) {
            ssoDeeplink.execute();
        }
```

3 The login form pop up, instead of showing the scope grant screen
4 After rebooting phone, SSO works fine again.

**Comment by tyvsmith** [comment]
Do you also login at step 2? Because if you don't login, Step 3 should be to show the login screen.

**Comment by jaredzhang** [comment]
@tyvsmith  before step 2, I login in Uber app already

**Comment by tyvsmith** [comment]
Ok, this is related to the task affinity on Android. This can be worked around by killing your running application process, but will be fixed permanently in a future version of the Uber app.

**Comment by tyvsmith** [comment]
We have released the [new rider app](https://newsroom.uber.com/newriderapp/) which should systematically address this issue. As it incrementally rolls out, this will be no longer be an issue. Closing this thread.
