### ISSUE TITLE
How to call products, estimates/price and estimates/time endpoints

### ISSUE THREAD

**Issue by qadirsuh** [uber/rides-android-sdk#55]
First I must thank for this awesome Uber SDK,

I need to integrate the uber endpoints in my app

- products ==> https://developer.uber.com/docs/rides/api/v1-products
- estimates/price ==> https://developer.uber.com/docs/rides/api/v1-estimates-price 
- estimates/time ==>  https://developer.uber.com/docs/rides/api/v1-estimates-time

as the above mentioned endpoints does't require any User authentication. Right?

how can I request these standalone API's with this sdk without authentication?

**Comment by itstexter** [comment]
Hey @qadirsuh,

As stated in the README, You can make a `Session` with a server token use it to make a `RidesService`. 

```
SessionConfiguration config = new SessionConfiguration.Builder()
  .setClientId("YOUR_CLIENT_ID")
  .setServerToken("YOUR_SERVER_TOKEN")
  .build();
ServerTokenSession session = new ServerTokenSession(config);
RidesService service = UberRidesApi.with(session).createService();
```

Going forward please use StackOverflow for integration questions. Uber developers actively monitor the `uber-api` tag on StackOverflow. If you need help installing or using the library, you can ask a question there. Make sure to tag your question with `uber-api` and `android`.

**Comment by qadirsuh** [comment]
Thanks for your suggestion, I will use the stackoverflow with tag uber-api
I am getting error on createService() method i.e `Cannot resolve method 'createService()'`

Any hint please.

**Comment by qadirsuh** [comment]
this worked
`RidesService service = UberRidesApi.with(session).build().createService();`

please update in your README.md
