### ISSUE TITLE
RideParameters .setPickupLocation or .setDropoffLocation with only latitude and longitude

### ISSUE THREAD

**Issue by saintjab** [uber/rides-android-sdk#56]
Hi guys, is it possible to just set PickupLocation or DropoffLocation with only latitude and longitude? The current implementation to supply address and nick means we have to use reverse geocoding to get address

**Comment by itstexter** [comment]
Hey Jonas,

I believe you should be able to just pass in null for both the address and
nickname when constructing RideParameters, as annotated on the methods.
