### ISSUE TITLE
Webpage not available

### ISSUE THREAD

**Issue by saintjab** [uber/rides-android-sdk#60]
So I am trying to use the RideRequest button without having the Uber app installed. It opened the web login screen where  entered my login details and then Webpage not available showed up. Attached is the screenshot of the error. What might I be doing wrong?

Details of my implementation,my  Fragment implements RideRequestButtonCallback but I don't get any errors logged though.

configuration = new SessionConfiguration.Builder()
                .setRedirectUri(REDIRECT_URI)
                .setClientId(CLIENT_ID)
                .setServerToken(SERVER_TOKEN)
                .setScopes(Arrays.asList(Scope.RIDE_WIDGETS))
                .setEnvironment(SessionConfiguration.Environment.SANDBOX)
                .build();
        UberSdk.initialize(configuration);

        ServerTokenSession session = new ServerTokenSession(configuration);
        RideParameters rideParametersCheapestProduct = new RideParameters.Builder()
                .setPickupLocation(PICKUP_LAT, PICKUP_LONG, PICKUP_NICK, null)
                .setDropoffLocation(DROP_LAT, DROP_LONG,DROP_NICK, null)
                .build();

        RideRequestButton uberButton = (RideRequestButton) v.findViewById(R.id.btnUber);
        RideRequestActivityBehavior rideRequestActivityBehavior = new RideRequestActivityBehavior(getActivity(),
                WIDGET_REQUEST_CODE, configuration);
        uberButton.setRequestBehavior(rideRequestActivityBehavior);
        uberButton.setRideParameters(rideParametersCheapestProduct);
        uberButton.setSession(session);
        uberButton.loadRideInformation();
        uberButton.setCallback(this);

![screenshot_2016-11-06-00-17-47 1](https://cloud.githubusercontent.com/assets/9318267/20034516/93a51f40-a3b8-11e6-88cb-54920571d28c.png)

**Comment by AshishYadav1992** [comment]
Facing same issue on login. Can you explain how to resolve this ? I think it is coming due to redirect uri but i m not sure what redirect uri has to place 
![unnamed-1](https://cloud.githubusercontent.com/assets/23651728/20515369/552310fe-b0b7-11e6-91cf-3b3fb8d58075.png)

**Comment by saintjab** [comment]
You are right. Check the issue you opened, I had provided my solution there. #63
