### ISSUE TITLE
Is loginWithScopes() method deprecated?

### ISSUE THREAD

**Issue by Vignatus** [uber/rides-android-sdk#62]
Could not find the aforementioned method. I am using 'com.uber.sdk:rides-android:0.5.3'. I am performing a custom integration of login where the login page is shown but the scopes are not shown to the user.

**Comment by tyvsmith** [comment]
loginWithScopes has been deprecated for a while. Please see configuring the Session to specify scopes. https://github.com/uber/rides-android-sdk#sdk-configuration
