### ISSUE TITLE
WebPage Not Available 

### ISSUE THREAD

**Issue by AshishYadav1992** [uber/rides-android-sdk#63]
On login i facing this issue how to resolve this 

    SessionConfiguration configuration = new SessionConfiguration.Builder()
                .setClientId("<>")
                .setRedirectUri("zippcab://ZippCab")
                .setServerToken("<>")
                .setClientSecret("<>")
                .setEnvironment(SessionConfiguration.Environment.PRODUCTION)
                .setEndpointRegion(SessionConfiguration.EndpointRegion.WORLD)
                .setScopes(Arrays.asList(Scope.PROFILE, Scope.REQUEST))
                .build();

        UberSdk.initialize(configuration);

  accessTokenManager = new AccessTokenManager(berLogin.this);

        mUberLoginManager = new LoginManager(accessTokenManager,
                new SampleLoginCallback(),
                configuration,
                1);

        mUberLoginManager.loginForAuthorizationCode(berLogin.this);
 
        mUberLoginManager.setRedirectForAuthorizationCode(true);

![unnamed-1](https://cloud.githubusercontent.com/assets/23651728/20515443/b81cb048-b0b7-11e6-9f8d-42b9dc5398df.png)

**Comment by saintjab** [comment]
@AshishYadav1992 since it is an app instead of a website, change your redirect url to http://localhost. That fixed a similar problem I was having. Thanks

**Comment by AshishYadav1992** [comment]
Still facing same issue not able to login and that webpage is coming

**Comment by saintjab** [comment]
You need to change the redirect url on the Developer Dashboard as well to http://localhost

**Comment by AshishYadav1992** [comment]
I already did on both side android code and Uber Dev Dashboard

**Comment by dustinwhittle** [comment]
You will need to update the `.setRedirectUri()` with 'http://localhost' and confirm it matches the dashboard. Once you update your app you will not be redirected to the unknown uri.

**Comment by dustinwhittle** [comment]
If it still doesn't work, can you please post on [stackoverflow](https://stackoverflow.com/questions/ask?tags=uber-api).

**Comment by AshishYadav1992** [comment]
I already did this on android code and after adding 'http://localhost' i m facing new error 
![unnamed-2](https://cloud.githubusercontent.com/assets/23651728/20551508/06116690-b167-11e6-8aa7-f9d8d9221859.png)
