### ISSUE TITLE
Empty AndroidHttpClient get compiled when using core-android 0.5.4 leading to unresolved references to actual methods of AndroidHttpClient

### ISSUE THREAD

**Issue by mjsachin** [uber/rides-android-sdk#65]
Warning:com.whizdm.restclient.CoreClient: can't find referenced method 'long getMinGzipSize(android.content.ContentResolver)' in program class android.net.http.AndroidHttpClient
Warning:com.whizdm.restclient.CoreClient: can't find referenced method 'org.apache.http.entity.AbstractHttpEntity getCompressedEntity(byte[],android.content.ContentResolver)' in program class android.net.http.AndroidHttpClient
Warning:com.whizdm.restclient.CoreClient: can't find referenced method 'java.io.InputStream getUngzippedContent(org.apache.http.HttpEntity)' in program class android.net.http.AndroidHttpClient
Warning:there were 3 unresolved references to program class members.

**Comment by mjsachin** [comment]
source for ApacheHttpClient says... 

* Apache HTTP Client was deprecated and is no longer part of compile classpath.
 * Robolectic still links to it so an empty class is needed for compiling purposes.
 *
 * See Robolectric <a href="https://github.com/robolectric/robolectric/issues/1862">issue</a> for
 * details.

**Comment by tyvsmith** [comment]
Thanks for reporting, we're looking into this.

**Comment by tyvsmith** [comment]
This is resolved with the latest release
