### ISSUE TITLE
How to Logout?

### ISSUE THREAD

**Issue by nidhiAscra** [uber/rides-android-sdk#67]
How do I add  or find logout button inside ubar sdk.

**Comment by agraebe** [comment]
@nidhiAscra If you're asking about how to generally maintain a UX that leverages the user information (if there is any), it highly depends on your code base. 

However, you can simple have a button that removes that token you obtained for that user with the [removeAccessToken](https://github.com/uber/rides-android-sdk/blob/f3ae76c3d7d5c176214f42557e535d3459219baa/core-android/src/main/java/com/uber/sdk/android/core/auth/AccessTokenManager.java#L141) method.

If you also want to *revoke* the access by invalidating the current token, you should call the  [/revoke endpoint as documented here](https://developer.uber.com/docs/trip-experiences/guides/authentication#revoking-tokens). I created an [enhancement request](https://github.com/uber/rides-android-sdk/issues/68) for this, so one could simply use a method provided by the SDK to accomplish that.

Let me know if you have further questions.
