### ISSUE TITLE
LoginManager breaks when used with Rides SDK 0.6.0

### ISSUE THREAD

**Issue by apkelly** [uber/rides-android-sdk#71]
If I use the Rides SDK 0.6.0 (needed to get extra details about a ride, e.g. pickup ETA) with v0.5.4 of the Android library you get a crash when the login manager is used to authenticate a user.

This is because of the following line (180 in LoginManager)

```java
.authority(ENDPOINT + "." + configuration.getEndpointRegion().domain)
```

The domain attribute is private and can't be accessed here, this line needs to be changed to use the getDomain() method on the enum.

Thanks.

**Comment by tyvsmith** [comment]
Thanks for reporting. We have a .6 for the SDK planned this week with the new dependency, so it should resolve your issue. I'll close the issue when we push that out.

**Comment by tyvsmith** [comment]
This should be resolved with the latest release.
