### ISSUE TITLE
"oauth/v2/authorize" gives wrong code for first time

### ISSUE THREAD

**Issue by amanflo** [uber/rides-android-sdk#75]
When I hit this "oauth/v2/authorize" url. I am  getting error "invalid_grant". 
Scenario when it works well :

* when I login again 
* when Uber app installed on user device with already login into Uber app

Scenario when it doesn't work :
 * For 1st time login 
 * when don't have Uber app with already login
 
Note: redirect_uri are same in response of above url & dashboard url for redirect

**Comment by dustinwhittle** [comment]
Hi, Can you please post this issue to stackoverflow with the tag "uber-api"?  https://stackoverflow.com/questions/tagged/uber-api

Can you share the exact implementation/code and requests/responses (without any sensitive credentials)?

**Comment by dustinwhittle** [comment]
If you get {"error": "invalid_grant"} then this means the code inside the query parameter code has already been used once or has become invalid.
