### ISSUE TITLE
If uber app is preinstalled then opening wber widget shows authentication failure.

### ISSUE THREAD

**Issue by bs2015** [uber/rides-android-sdk#77]
If uber app is preinstalled then opening wber widget shows authentication failure. I am using sanbox. Any suggestion would be helpful.

**Comment by bs2015** [comment]
![image](https://cloud.githubusercontent.com/assets/13464551/25496177/96d908bc-2b9d-11e7-80b6-0937bc3c72c5.png)

**Comment by itstexter** [comment]
Hey @bs2015 when using the widget if the Uber App is installed it by default will try to use Single Sign On (SSO) for a more pleasant user experience. You probably haven't configured your app to use SSO but you can do so by following our [developer docs on authentication](https://developer.uber.com/docs/riders/guides/authentication/introduction#single-sign-on-sso).

**Comment by bs2015** [comment]
@itstexter Thank a lot for quick response. Yes, I have skipped that! I will try that.

**Comment by bs2015** [comment]
Adding android app signature for SSO solved my issue. Thanks bro!
