### ISSUE TITLE
Unable to signup using widget (version 0.6.1)

### ISSUE THREAD

**Issue by buddhasaikia** [uber/rides-android-sdk#80]
Hi, I am getting authentication error while trying to signup using ride request widget. Login process is working perfectly. Also I am not able to see any logs on console. Any help would be greatly appreciated!

![device-2017-06-05-121846](https://cloud.githubusercontent.com/assets/13464551/26773699/0b8ceb64-49ea-11e7-90e2-5c6c3c719dd4.png)

![device-2017-06-05-113240](https://cloud.githubusercontent.com/assets/13464551/26773704/12a73c6a-49ea-11e7-8d6c-01c187cf8db5.png)

**Comment by bs2015** [comment]
This is happening when Uber app is not installed.

**Comment by tyvsmith** [comment]
This should no longer be an issue.
