### ISSUE TITLE
There was an error processing your request. Please try again

### ISSUE THREAD

**Issue by Tazovsky** [uber/rides-android-sdk#83]
Uber app doesn’t work on my `Vernee Mars Pro`. I  submit ticket through app, but after couple of hard reset of my profile it didn’t help. Then I heard from my friend – who bought Vernee Thor E – that she has exactly same problem. Then I tried dozen of older version of uber app but but I always got same error while booking a ride: `There was an error processing your request. Please try again.` If there is anything to provide more info about bug - just let me know what do you need.

![2d4a4a29-f09b-4ab0-a5eb-a6c95b3f8f13image](https://user-images.githubusercontent.com/29068994/30320286-7dab7bd2-97b2-11e7-9054-6624c1c84b35.jpg)
![screenshot_20170911-095834](https://user-images.githubusercontent.com/29068994/30320287-7dacd072-97b2-11e7-8ea3-8a42938ebe3d.png)
![screenshot_20170911-095822](https://user-images.githubusercontent.com/29068994/30320288-7dad0a7e-97b2-11e7-8a0a-d9d2d10f9b41.png)

**Comment by tyvsmith** [comment]
Please seek proper support channels.
