### ISSUE TITLE
Login webView crashes on load, sdk 0.6.1, Android 6.0+ devices

### ISSUE THREAD

**Issue by luckcoolla** [uber/rides-android-sdk#87]
I've worked with uber android sdk last 6 month and two days ago I see web login form stopped work on Android 6.0 devices - there is some error occurs(details are below) during just the page loading, right after Facebook button showing. Same code without changes has worked for me last 5 month on same devices and it's still working for android devices with versions 4.1-5.1.

I'm using com.uber.sdk.android.core.auth.LoginManager#loginForAuthorizationCode method.

Error: net::ERR_NAME_NOT_RESOLVED, code: -2
Stack trace: 
```
"main@16225" prio=5 runnable
  java.lang.Thread.State: RUNNABLE
	  at com.uber.sdk.android.core.auth.LoginActivity$OAuthWebViewClient.onReceivedError(LoginActivity.java:223)
	  at com.android.webview.chromium.WebViewContentsClientAdapter.onReceivedError2(WebViewContentsClientAdapter.java:235)
	  at org.chromium.android_webview.AwContentsClientCallbackHelper$MyHandler.handleMessage(AwContentsClientCallbackHelper.java:38)
	  at android.os.Handler.dispatchMessage(Handler.java:102)
```
Screenshot of the error with its description 
<img width="1277" alt="screen shot 2017-10-13 at 11 57 22 am" src="https://user-images.githubusercontent.com/3755157/31538383-11b7f81e-b00e-11e7-9516-cdbfe24d8c83.png">

Screenshot of the page on the breakpoint:
![device-2017-10-13-115019](https://user-images.githubusercontent.com/3755157/31538460-4ace12c8-b00e-11e7-8f6c-3696b95cb009.png)

Devices, used for test:

- Samsung Galaxy S6, SM-920F, Android 6.0.1
- Samsung Galaxy S7, sm-g930f, Android 6.0.1
- HTC Nexus 9, Android 7.0

**Comment by luckcoolla** [comment]
@tyvsmith Any comment? I still see the issue

**Comment by tyvsmith** [comment]
Yeah, please update to the latest and use the chrometabs impl.

**Comment by luckcoolla** [comment]
Thank you!
