### ISSUE TITLE
how to generate access token using the authorization code?

### ISSUE THREAD

**Issue by msayanece** [uber/rides-android-sdk#88]
I am configuring uber sdk with Request scope (Restricted). In the LoginManager callback method onAuthorizationCodeReceived() I am getting authorizationCode as a parameter, whereas the onLoginSuccess() callback method is not being called. I am stuck here. Without Request scope the onLoginSuccess() being called, but then I cannot request a ride successfully as the scope is missing.

**Comment by tyvsmith** [comment]
I just merged an implementation using the Standard redirect URI pattern against Custom Tabs and the Browser. 

This should simplify the use of the Auth Code flow. See https://github.com/uber/rides-android-sdk/commit/1c083598b249c05f804210b928df591bbebf93cd

I'll be cutting a build of that tomorrow.
