### ISSUE TITLE
AccessTokenAuthenticator cause NPE

### ISSUE THREAD

**Issue by VMitin** [uber/rides-android-sdk#89]
Hi there. 

We are using the Uber SDK in our application and one of the users have sent the bug report. 

Please, look at the deobfuscated StackTrace:
> Exception java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.uber.sdk.core.auth.AccessToken.getToken()' on a null object reference
>         at com.uber.sdk.core.auth.AccessTokenAuthenticator createBearerToken(com.uber.sdk.core.auth.AccessToken)(AccessTokenAuthenticator.java)
>         at com.uber.sdk.core.auth.AccessTokenAuthenticator setBearerToken(okhttp3.Request$Builder,com.uber.sdk.core.auth.AccessToken)(AccessTokenAuthenticator.java)
>         at com.uber.sdk.core.auth.AccessTokenAuthenticator signRequest(okhttp3.Request$Builder)(AccessTokenAuthenticator.java)
>         at com.uber.sdk.rides.client.internal.ApiInterceptor.okhttp3.Response intercept(okhttp3.Interceptor$Chain)(ApiInterceptor.java)
>         at okhttp3.internal.http.RealInterceptorChain.proceed ()
>         at okhttp3.internal.http.RealInterceptorChain.proceed ()
>         at okhttp3.RealCall.getResponseWithInterceptorChain ()
>         at okhttp3.RealCall.access$100 ()
>         at okhttp3.RealCall$AsyncCall.execute ()
>         at okhttp3.internal.NamedRunnable.run ()
>         at java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1162)
>         at java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:636)
>         at java.lang.Thread.run (Thread.java:764)

I do not know why this happens, but I see that:
1. The method AccessTokenStorage.getAccessToken() marked as @Nullable
2. In the AccessTokenAuthenticator there is no checking OAuth2Token on null. 

To my mind, any NPE it is a bug. We will catch this NPE and will ask the user to re-login.

Have a nice day.

**Comment by tyvsmith** [comment]
This is fixed in master in our java repo.

**Comment by tyvsmith** [comment]
This is now deployed in the Android (0.9.1) and Java SDK (0.8.0)
